###
GET  http://localhost:4000/api/employees
###
POST http://localhost:4000/api/employees
Content-Type: application/json

{
    "name": "Lucia",
    "position": "Jr. Developer",
    "office": "New York",
    "salary": 10000
}

###
GET http://localhost:4000/api/employees/615b7a66969184d2df704311

###
DELETE http://localhost:4000/api/employees/615b7a94bf0ec241abd934eb

###
PUT http://localhost:4000/api/employees/615b7b07120d55e44a423138
Content-Type: application/json

{
    "salary": 15000
}